### ISSUE TITLE
After rotating a rectangular image, croppedAreaPixel range can be negative

### ISSUE THREAD

**Issue by smb2268** [ricardo-ch/react-easy-crop#240]
**Describe the bug**
When rotating a rectangular image, the x and y coordinates of the croppedArea no longer align within the width and height values.

**To Reproduce**
1. Go to https://codesandbox.io/s/cocky-pare-zdopi?file=/src/index.js
2. Click on Rotate
3. Drag the image so that the top left corner of the image is aligned with the top left corner of the crop area
4. Notice that the croppedAreaPixels is now `{width: 473, height: 355, x: 163, y: -163}` when I would think it should be `{width: 473, height: 355, x: 0, y: 0}`

**Expected behavior**
I would expect that the x value of `croppedAreaPixels` is between 0 and 473 and the y value is between 0 and 355 as we drag the image around the crop area.

**Comment by ValentinH** [comment]
I understand this is misleading but it actually depends on the order in which you do the operations. If you check our sandbox example where we output the end result (also our demo website), it actually produces the right output.

To be honest, I didn't implement this part so I'm not willing to change it. However, if you are interested to make this change while still keeping the right output on the demo, I'd be happy to review a PR.

**Comment by BenMorel** [comment]
Same issue here. @smb2268 did you figure out what the `163px` offset corresponds to?

In your case your "zero" is at `{x: 163, y: -163}`; in my case it's `{x: 196, y: -196}`, but I can't map it to a combination of the original picture dimensions and the cropped area dimensions.

**Comment by BenMorel** [comment]
Found it. It's `ceil(abs(naturalWidth - naturalHeight) / 2)`.

**Comment by BenMorel** [comment]
Working method to get close (within a 1~2px range) to a `{x: 0, y: 0}` at the top-left corner when rotating at -90° or 90° angle:

```js
/**
 * @param {Object} mediaSize         The media size as returned by react-easy-crop
 * @param {Object} croppedAreaPixels The cropped area as returned by react-easy-crop
 * @param {number} angle             The angle, 0|90|180|270
 */
const fixCroppedAreaPixels = (mediaSize, croppedAreaPixels, angle) => {
    if (angle === 90 || angle === 270) {
        const offset = ((mediaSize.naturalWidth - mediaSize.naturalHeight) / 2) ^ 0; // round towards zero

        croppedAreaPixels.x -= offset;
        croppedAreaPixels.y += offset;
    }

    return croppedAreaPixels;
};
```

**Comment by BenMorel** [comment]
And full working method to reproject the coordinates on the original image, **before rotation**:

```js
/**
 * @param {Object} mediaSize         The media size as returned by react-easy-crop
 * @param {Object} croppedAreaPixels The cropped area as returned by react-easy-crop
 * @param {number} angle             The rotation angle, 0|90|180|270
 */
const projectCropAreaPixelsOnOriginalImage = (mediaSize, croppedAreaPixels, angle) => {
    if (angle === 90 || angle === 270) {
        const offset = ((mediaSize.naturalWidth - mediaSize.naturalHeight) / 2) ^ 0; // round towards zero

        croppedAreaPixels.x -= offset;
        croppedAreaPixels.y += offset;
    }

    const imageW = mediaSize.naturalWidth;
    const imageH = mediaSize.naturalHeight;

    let cropAreaX = croppedAreaPixels.x;
    let cropAreaY = croppedAreaPixels.y;

    const cropAreaW = croppedAreaPixels.width;
    const cropAreaH = croppedAreaPixels.height;

    let ax, ay, bx, by;

    if (angle === 0) {
        ax = cropAreaX;
        ay = cropAreaY;

        bx = cropAreaX + cropAreaW - 1;
        by = cropAreaY + cropAreaH - 1;
    } else if (angle === 90) {
        ax = cropAreaY;
        ay = imageH - cropAreaW - cropAreaX;

        bx = cropAreaH + cropAreaY - 1;
        by = imageH - cropAreaX - 1;
    } else if (angle === 180) {
        ax = imageW - cropAreaX - cropAreaW;
        ay = imageH - cropAreaY - cropAreaH;

        bx = imageW - cropAreaX + 1;
        by = imageH - cropAreaY + 1;
    } else if (angle === 270) {
        ax = imageW - cropAreaY - cropAreaH;
        ay = cropAreaX;

        bx = imageW - cropAreaY - 1;
        by = cropAreaW + cropAreaX - 1;
    }

    // rounding is not always predictable and coordinates may exceed the bounds of the image by 1 or 2 px
    ax = Math.max(ax, 0);
    ay = Math.max(ay, 0);
    bx = Math.max(bx, 0);
    by = Math.max(by, 0);
    ax = Math.min(imageW - 1, ax);
    ay = Math.min(imageH - 1, ay);
    bx = Math.min(imageW - 1, bx);
    by = Math.min(imageH - 1, by);

    return { left: ax, top: ay, right: bx, bottom: by };
};
```

There may be ~1px or ~2px rounding errors, but it works relatively well.

**Comment by ValentinH** [comment]
@BenMorel as you seem to have good mathematical knowledge around these transformations, if you are interested, you could update the library logic to have this rotated coordinates matching what's asked in this issue. 

I think it makes sense and as long as we are able to update to cropping logic on the demo to work, I'm happy to do a breaking change here.

**Comment by BenMorel** [comment]
@ValentinH Cool! I'll see if I can find some time to draft a PR. However I think there is some hidden complexity to this, in particular with rotations not a multiple of 90 (and I think there's an issue with my approach when the crop area is not a square, too).

I'd be curious to see if other people are *expecting* the current format? It may be OK to draw on a canvas as you did, but quite hard to translate to image resizing services such as Thumbor, which we're using.

**Comment by ValentinH** [comment]
This should be fixed with v4.0.0. Please comment if not 🙂

**Comment by thomik-corp** [comment]
This is not fixed. I am playing with it here: https://codesandbox.io/p/sandbox/react-easy-crop-with-live-output-forked-dpsxy3?file=%2Fsrc%2FApp.jsx%3A61%2C8. You will need to make some changes as I am currently experimenting with this code. FWIW I am trying to use CSS transforms to get to end result rather than extracting an image via canvas API.

**Comment by ValentinH** [comment]
This demo might be interesting for you then: https://codesandbox.io/s/react-easy-crop-with-live-output-kkqj0

**Comment by thomik-corp** [comment]
That was the base demo that I forked and it does not have a rotation in it. The moment I added rotation it messed up height width and rotate output. Any clues?

**Comment by ValentinH** [comment]
The library is internally using transforms to display the image in the cropper.
Therefore, instead of using the croppedAreaPixels output, you can use the crop.x, crop.y and rotation values that you are passing to the cropper.
